### ISSUE TITLE
jsreport.config.json is not used

### ISSUE THREAD

**Issue by robindijkhof** [jsreport/jsreport-gcloud-functions-starter-kit#1]
This file is never used. I think it should be removed to prevent confusion.

**Comment by pofider** [comment]
It is used when you develop your templates locally.
https://jsreport.net/learn/gcloud-functions-serverless#develope-your-templates

**Comment by robindijkhof** [comment]
@pofider I don't think so. There is no reference to the file in the project. Also, I tried changing the port number which does not work. Last, the file is not used in the init like prod config. It think it should be removed or the first couple of lines in server.js should be changed to this:

    const path = require('path')
    const jsreport = require('jsreport')({
      configFile: path.join(__dirname, 'jsreport.config.json')
    })
    const fs = require('fs')

**Comment by pofider** [comment]
jsreport actually defaults to the `jsreport.config.json` and loads it.
If I clone this report, run `npm i`, and change port in `jsreport.config.json` and run with `node server.js`. It uses the updated port.

The `index.js` is used in google cloud runtime, but `server.js` is used when developing templates to start jsreport.

**Comment by robindijkhof** [comment]
That makes sense. My config wasn't in the root dir.
